cache:
  paths:
    - /api/node_modules/
    - /frontend/node_modules/


stages:
  - test

api-endpoints:
  image: node:14.3.0
  stage: test
  variables:
    NODE_ENV: test
  before_script:
    - cd /builds/it2810-h20/team-72/prosjekt-3/api
    - npm install
  script:
    - cd /builds/it2810-h20/team-72/prosjekt-3/api
    - npm test

frontend-cypress-e2e-chrome:
  image: cypress/browsers:chrome69
  stage: test
  script:
    - cd /builds/it2810-h20/team-72/prosjekt-3/frontend
    - npm install
    - $(npm bin)/cypress run --browser chrome
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - cypress/screenshots
    - cypress/videos
    reports:
      junit:
        - results/TEST-*.xml

