stages:
  - test

services:
  - postgres:latest
variables:
  POSTGRES_DB: test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  NODE_ENV: test

api-endpoints-test:
  image: node:14.3.0
  stage: test
  before_script:
    - cd /builds/it2810-h20/team-72/prosjekt-3/api
    - npm install
  script:
    - cd /builds/it2810-h20/team-72/prosjekt-3/api
    - npm test

frontend-e2e-test:
  image: cypress/base:14
  stage: test
  before_script:
      - cd /builds/it2810-h20/team-72/prosjekt-3/api
      - npm install
      - npm run schema:sync
      - npm run seed:run
      - npx pm2 start npm -- start
  script:
    - cd /builds/it2810-h20/team-72/prosjekt-3/frontend
    - npm ci
    # check Cypress binary path and cached versions
    - npx cypress cache path
    - npx cypress cache list
    - npm run cypress:verify
    # Run tests
    - export CYPRESS_API_SERVER="http://localhost:8000/api"
    - export REACT_APP_API_SERVER="http://localhost:8000/api"
    - npm test

frontend-unit-test:
  image: cypress/base:14
  stage: test
  script:
    - cd /builds/it2810-h20/team-72/prosjekt-3/frontend
    - npm ci
    - npm run jest
