cache:
  paths:
    - /node_modules/

stages:
  - test

unit_test:
  image: node
  stage: test
  variables:
    NODE_ENV: test
  before_script:
    # Install npm
    - npm install
  script:
    - npm test
    - npx prettier .c .
